version: '3.5'

services:
  api:
    container_name: api
    restart: always
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  client:
    container_name: react
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - "api:api"
    ports:
      - '80:80'
    